# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "sles12"
  config.vm.synced_folder "../../../", "/installer"
  config.vm.provision :shell, :path => "./bootstrap.sh"
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "384"]
  end
  # requires zypper install gcc kernel-default-devel to compile
  config.vbguest.auto_update = true
end
