# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian-7"
  config.vm.box_url = "https://github.com/jose-lpa/packer-debian_7.6.0/releases/download/1.0/packer_virtualbox-iso_virtualbox.box"
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "384"]
  end
  config.vm.synced_folder "../../../../", "/vagrant"
  config.vm.provision :shell, :path => "./bootstrap.sh"
  config.vm.network :forwarded_port, guest: 6000, host: 6000
end
